on:
  # Trigger analysis when pushing to master or main branches, and when creating a pull request.
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, reopened]

name: SonarQube Scan

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving the relevancy of reporting.
        fetch-depth: 0
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: Test  # Add your project key here
